# Generated by Django 3.2 on 2021-06-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_number', models.IntegerField(max_length=30, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_charge', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default='none', max_length=30)),
                ('status', models.CharField(choices=[('paid', 'PAID'), ('pending', 'PENDING'), ('sent', 'SENT'), ('refunded', 'REFUNDED'), ('finalized', 'FINALIZED')], default='pending', max_length=99)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=30, unique=True)),
                ('tel_num', models.CharField(default=0, max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Man',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=30, unique=True)),
                ('tel_num', models.CharField(default=0, max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(default='none', max_length=30)),
                ('city', models.CharField(default='none', max_length=30)),
                ('street', models.CharField(default='none', max_length=30)),
                ('building', models.CharField(default='none', max_length=30)),
                ('floor', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=30, unique=True)),
                ('tel_num', models.CharField(default=0, max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='none', max_length=30)),
                ('unit_price', models.PositiveIntegerField(default='none')),
                ('unit_mass', models.PositiveIntegerField(default='none')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=30, unique=True)),
                ('tel_num', models.CharField(default=0, max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.customer')),
                ('driver_in', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_in', to='DeliveryApp.delivery_man')),
                ('driver_out', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_out', to='DeliveryApp.delivery_man')),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_from', to='DeliveryApp.location')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_to', to='DeliveryApp.location')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.delivery'),
        ),
        migrations.AddField(
            model_name='bill',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DeliveryApp.manager'),
        ),
    ]
